# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cache_pb2 as cache__pb2


class CacheStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.obtener_sala = channel.unary_unary(
                '/cache.Cache/obtener_sala',
                request_serializer=cache__pb2.Consulta.SerializeToString,
                response_deserializer=cache__pb2.Respuesta.FromString,
                )
        self.guardar_sala = channel.unary_unary(
                '/cache.Cache/guardar_sala',
                request_serializer=cache__pb2.Consulta.SerializeToString,
                response_deserializer=cache__pb2.Respuesta.FromString,
                )


class CacheServicer(object):
    """Missing associated documentation comment in .proto file."""

    def obtener_sala(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def guardar_sala(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CacheServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'obtener_sala': grpc.unary_unary_rpc_method_handler(
                    servicer.obtener_sala,
                    request_deserializer=cache__pb2.Consulta.FromString,
                    response_serializer=cache__pb2.Respuesta.SerializeToString,
            ),
            'guardar_sala': grpc.unary_unary_rpc_method_handler(
                    servicer.guardar_sala,
                    request_deserializer=cache__pb2.Consulta.FromString,
                    response_serializer=cache__pb2.Respuesta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cache.Cache', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Cache(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def obtener_sala(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cache.Cache/obtener_sala',
            cache__pb2.Consulta.SerializeToString,
            cache__pb2.Respuesta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def guardar_sala(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cache.Cache/guardar_sala',
            cache__pb2.Consulta.SerializeToString,
            cache__pb2.Respuesta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
